### PR TITLE
Explicitly specify CodeSandbox template

### PR DESCRIPTION
**Pull request by gomorizsolt**

### CODE REVIEW

**Comment by gomorizsolt** [comment]
Can anyone else verify the repo does work in CodeSandbox if the template is explicitly verified?

**Comment by thisismydesign** [comment]
Doesn't seem to work for me. You can verify by modifying the URL: https://codesandbox.io/s/github/gomorizsolt/firebase-auth-starter/tree/specifiy-sandbox-template

**Comment by gomorizsolt** [comment]
> Doesn't seem to work for me. You can verify by modifying the URL: https://codesandbox.io/s/github/gomorizsolt/firebase-auth-starter/tree/specifiy-sandbox-template

I assume it's because there's no configuration provided:

https://github.com/componently-com/firebase-auth-starter/blob/44cb77bed2b6f2bd8ea1a7b8d9716a1a87fdfdea/index.html#L11

**Comment by thisismydesign** [comment]
Good point, it works, thanks!

**Comment by gomorizsolt** [comment]
Cool! As discussed, it's sufficient to commit these credentials for now, right?

**Comment by thisismydesign** [comment]
Yes. For this example I'll take care of it.

**Pull request merged**
